// apps/http-mfe-react/src/app/home/home.tsx
import styles from './home.module.scss';
import reactLogo from '../../assets/logo-react.png';

/* eslint-disable-next-line */
export interface HomeProps {}

export function Home(props: HomeProps) {
  return (
    <div className={styles['container']}>
      <div className='h1-container'>
        <h1>MONOREPO REACT 18.2.0 MFE</h1>
        <img src={reactLogo} alt="logo-react" />
      </div>
    </div>
  );
}

export default Home;

// apps/host-angular/src/app/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent {}

<div class="h1-container">
  <h1>MONOREPO ANGULAR ~16.0.0 HOST</h1>
  <img src="../../assets/logo-angular.png" alt="logo-angular" />
</div>
